In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

In [4]:
import this
a=5

In [5]:
print(a)

5

In [6]:
a

5

In [7]:
import pandas as pd

In [8]:
pd.__version__

'3.0.1'

In [9]:
import numpy as np

In [ ]:
sales = [100, 200, 150]

new_sales = []

for value in sales:
    new_sales.append(value * 1.2)

new_sales

[120.0, 240.0, 180.0]

In [11]:
import pandas as pd

data = {
    "name": ["Anna", "David", "Mariam"],
    "revenue": [150, 220, 90],
    "city": ["Yerevan", "Tbilisi", "Warsaw"]
}

df = pd.DataFrame(data)
df

     name  revenue     city
0    Anna      150  Yerevan
1   David      220  Tbilisi
2  Mariam       90   Warsaw

In [12]:
t = 0.2
df["revenue_after_tax"] = df["revenue"] * (1 - t)
df

     name  revenue     city  revenue_after_tax
0    Anna      150  Yerevan              120.0
1   David      220  Tbilisi              176.0
2  Mariam       90   Warsaw               72.0