In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [2]:
px.defaults.template = "plotly_white"

In [3]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
             .sum()
)

monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [4]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px

In [5]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
             .sum()
)

monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [6]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot: Monthly Total Sales"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [7]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [8]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence=["#141313"]
)

fig.show()

In [9]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
             .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [10]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_sequence=["#3B6EAD", "#B0B8C7"]
)

fig.show()

In [11]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_map={
        "A": "#3B6EAD",
        "B": "#06090D"
    }
)

fig.show()

In [13]:
def my_bar_plot(
    df: pd.DataFrame, x_col: str, y_col: float, flag: bool = True
) -> px.bar:

    df_agg = df.groupby(x_col, as_index=False)[y_col].sum()

    if flag:
        flag_region = df_agg.loc[df_agg[y_col].idxmax(), x_col]
        df_agg["highlight"] = np.where(
            df_agg[x_col] == flag_region,
            f"Highest {y_col.capitalize()}",
            f"Other {y_col.capitalize()}",
        )
        colorizer = {
            f"Highest {y_col.capitalize()}": "#3B6EAD",
            f"Other {y_col.capitalize()}": "#D9D9D9",
        }
    else:
        flag_region = df_agg.loc[df_agg[y_col].idxmin(), x_col]
        df_agg["highlight"] = np.where(
            df_agg[x_col] == flag_region,
            f"Lowest {y_col.capitalize()}",
            f"Other {y_col.capitalize()}",
        )
        colorizer = {
            f"Lowest {y_col.capitalize()}": "#3B6EAD",
            f"Other {y_col.capitalize()}": "#D9D9D9",
        }

    fig = px.bar(
        df_agg,
        x=x_col,
        y=y_col,
        color="highlight",
        title=f"Total {y_col.capitalize()} by {x_col.capitalize()}",
        color_discrete_map=colorizer,
    )

    fig.update_traces(textposition="outside")

    fig.update_layout(
        xaxis_title=x_col.capitalize(),
        yaxis_title=y_col.capitalize(),
        legend_title="",
    )

    return fig

In [17]:
my_bar_plot(region_sales, "region", "sales",  flag=True)